// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/search-products.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.99.3";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/search-products.ts
var search_products_default = defineTool({
  name: "search_products",
  title: "\u0411\u0430\u0440\u0430\u0430 \u0445\u0430\u0439\u0445 (Search products)",
  description: "Search the EasyShop catalog by name, category or brand. Returns name, price, discount, stock and product URL slug.",
  inputSchema: {
    query: z.string().trim().min(1).optional().describe("Text to match against product name."),
    category: z.string().trim().min(1).optional().describe("Filter by category code/name."),
    on_sale: z.boolean().optional().describe("Only products currently on sale."),
    limit: z.number().int().min(1).max(50).default(10).describe("Max number of results.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, category, on_sale, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("products").select("id, name, slug, category, price, original_price, discount, is_on_sale, is_new, stock_quantity").eq("is_active", true).limit(limit ?? 10);
    if (query) q = q.ilike("name", `%${query}%`);
    if (category) q = q.eq("category", category);
    if (on_sale) q = q.eq("is_on_sale", true);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const items = (data ?? []).map((p) => ({
      ...p,
      url: `https://easyshop.mn/product/${p.slug}`
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { products: items, count: items.length }
    };
  }
});

// src/lib/mcp/tools/get-product.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^3.25.76";
var get_product_default = defineTool2({
  name: "get_product",
  title: "\u0411\u0430\u0440\u0430\u0430\u043D\u044B \u0434\u044D\u043B\u0433\u044D\u0440\u044D\u043D\u0433\u04AF\u0439 (Get product)",
  description: "Get full details for one product by its URL slug or id: price, description, colors, sizes and stock.",
  inputSchema: {
    slug: z2.string().trim().min(1).optional().describe("Product URL slug, e.g. 'hotbrush'."),
    id: z2.string().uuid().optional().describe("Product id (UUID).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug, id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    if (!slug && !id) {
      return { content: [{ type: "text", text: "Provide either `slug` or `id`." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("products").select(
      "id, name, slug, category, description, price, original_price, discount, is_on_sale, is_bogo, is_new, stock_quantity, colors, sizes, variant_stock, specifications, sales"
    ).eq("is_active", true).limit(1);
    q = id ? q.eq("id", id) : q.eq("slug", slug);
    const { data, error } = await q.maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "\u0411\u0430\u0440\u0430\u0430 \u043E\u043B\u0434\u0441\u043E\u043D\u0433\u04AF\u0439 (product not found)." }], isError: true };
    const product = { ...data, url: `https://easyshop.mn/product/${data.slug}` };
    return {
      content: [{ type: "text", text: JSON.stringify(product, null, 2) }],
      structuredContent: { product }
    };
  }
});

// src/lib/mcp/tools/list-my-orders.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^3.25.76";
var list_my_orders_default = defineTool3({
  name: "list_my_orders",
  title: "\u041C\u0438\u043D\u0438\u0439 \u0437\u0430\u0445\u0438\u0430\u043B\u0433\u0443\u0443\u0434 (List my orders)",
  description: "List the signed-in user's own orders with status, payment status, total and items.",
  inputSchema: {
    status: z3.string().trim().min(1).optional().describe("Filter by order status."),
    limit: z3.number().int().min(1).max(50).default(10).describe("Max number of orders.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("orders").select(
      "id, order_ref, status, payment_status, payment_method, total, delivery_fee, items, shipping_address, created_at, delivered_at"
    ).eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 10);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { orders: data ?? [], count: (data ?? []).length }
    };
  }
});

// src/lib/mcp/tools/track-order.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z4 } from "npm:zod@^3.25.76";
var track_order_default = defineTool4({
  name: "track_order",
  title: "\u0417\u0430\u0445\u0438\u0430\u043B\u0433\u0430 \u0445\u044F\u043D\u0430\u0445 (Track order)",
  description: "Get delivery and payment status for one of the signed-in user's orders by order reference or id.",
  inputSchema: {
    order_ref: z4.string().trim().min(1).optional().describe("Order reference, e.g. 'ES-260814-123456'."),
    id: z4.string().uuid().optional().describe("Order id (UUID).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ order_ref, id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    if (!order_ref && !id) {
      return { content: [{ type: "text", text: "Provide either `order_ref` or `id`." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("orders").select(
      "id, order_ref, status, payment_status, delivery_status, total, items, shipping_address, created_at, assigned_at, picked_up_at, delivered_at"
    ).eq("user_id", ctx.getUserId()).limit(1);
    q = id ? q.eq("id", id) : q.eq("order_ref", order_ref);
    const { data, error } = await q.maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "\u0417\u0430\u0445\u0438\u0430\u043B\u0433\u0430 \u043E\u043B\u0434\u0441\u043E\u043D\u0433\u04AF\u0439 (order not found)." }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { order: data }
    };
  }
});

// src/lib/mcp/tools/get-my-profile.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.2";
var get_my_profile_default = defineTool5({
  name: "get_my_profile",
  title: "\u041C\u0438\u043D\u0438\u0439 \u043F\u0440\u043E\u0444\u0430\u0439\u043B (My profile)",
  description: "Get the signed-in user's EasyShop profile: name, phone, address, loyalty points and referral code.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("profiles").select("full_name, phone, address, loyalty_points, referral_code, created_at").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "\u041F\u0440\u043E\u0444\u0430\u0439\u043B \u043E\u043B\u0434\u0441\u043E\u043D\u0433\u04AF\u0439 (no profile row)." }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { profile: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "jiqjebbxcwetakdhfuel";
var mcp_default = defineMcp({
  name: "homestore-mongolia",
  title: "HomeStore Mongolia",
  version: "0.1.0",
  instructions: "Tools for the EasyShop / HomeStore Mongolia online store. Search the product catalog, read product details, and read the signed-in customer's own profile and orders (including delivery tracking). Prices are in MNT (\u20AE).",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [search_products_default, get_product_default, list_my_orders_default, track_order_default, get_my_profile_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
